# Alembic configuration
# Run from server/ directory:
#
#   alembic init migrations
#   alembic revision --autogenerate -m "initial schema"
#   alembic upgrade head
#
# Then on subsequent model changes:
#   alembic revision --autogenerate -m "describe change"
#   alembic upgrade head

# alembic.ini is auto-generated by `alembic init`.
# Set sqlalchemy.url in alembic.ini to match your DATABASE_URL,
# or better: read it from .env dynamically in migrations/env.py:
#
# --- In migrations/env.py ---
# from server.config import get_settings
# config.set_main_option("sqlalchemy.url", get_settings().DATABASE_URL)
